name: Construir el sitio con Nikola

on:
  pull_request:
    branches: [ master ]
    paths: 
      - conf.py
      - pages/**
      - themes/**
      - plugins/**
      - images/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_freeze.txt
    - name: Buildear con Nikola
      run: |
        nikola build
