name: Construir el sitio con Nikola

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_freeze.txt
    - name: Buildear con Nikola
      run: |
        nikola build
    - name: Publicar pagina a GH Pages
      run: |
        nikola github_deploy